### ISSUE TITLE
Names for admins.

### ISSUE THREAD

**Issue by datakmart** [justinelliotmeyers/Kosovo_2018_Administrative_Boundaries#1]
I've created a shapefile with names.
[XK_EA_2018_with_name.zip](https://github.com/justinelliotmeyers/Kosovo_2018_Administrative_Boundaries/files/2303292/XK_EA_2018_with_name.zip)

**Comment by justinelliotmeyers** [comment]
thanks @datakmart ! I'll pull in the main repo and add a table.

**Comment by justinelliotmeyers** [comment]
data updated (*just uploaded your raw zip and attributed you as source for names). Thanks!! Justin
